export const dosageForms = [
  {name: 'PUFF', shortName: 'puff'},
  {name: 'AEROSOL, FOAM', shortName: 'AER FOAM'},
  {name: 'AEROSOL, METERED', shortName: 'AER MET'},
  {name: 'AEROSOL, POWDER', shortName: 'AER PWD'},
  {name: 'AEROSOL, SPRAY', shortName: 'AER SPRAY'},
  {name: 'BAR, CHEWABLE', shortName: 'BAR CHEW'},
  {name: 'BEAD', shortName: 'BEAD'},
  {name: 'BEAD, IMPLANT, EXTENDED RELEASE', shortName: 'BEAD IMP ER'},
  {name: 'BLOCK', shortName: 'BLOCK'},
  {name: 'CAPSULE', shortName: 'CAP'},
  {name: 'CAPSULE, COATED', shortName: 'CAP COATED'},
  {name: 'CAPSULE, COATED PELLETS', shortName: 'CAP COATED PELLETS'},
  {name: 'CAPSULE, COATED, EXTENDED RELEASE', shortName: 'CAP COATED ER'},
  {name: 'CAPSULE, DELAYED RELEASE', shortName: 'CAP DR'},
  {name: 'CAPSULE, DELAYED RELEASE PELLETS', shortName: 'CAP DR PELLETS'},
  {name: 'CAPSULE, EXTENDED RELEASE', shortName: 'CAP ER'},
  {
    name: 'CAPSULE, FILM COATED, EXTENDED RELEASE',
    shortName: 'CAP FILM COATED ER',
  },
  {name: 'CAPSULE, GELATIN COATED', shortName: 'CAP GELATIN COATED'},
  {name: 'CAPSULE, LIQUID FILLED', shortName: 'CAP LIQ FILLED'},
  {name: 'CORE, EXTENDED RELEASE', shortName: 'CORE ER'},
  {name: 'CREAM', shortName: 'CREAM'},
  {name: 'CREAM, AUGMENTED', shortName: 'CREAM AUG'},
  {name: 'CRYSTAL', shortName: 'CRYSTAL'},
  {name: 'DIAPHRAGM', shortName: 'DIAPHRAGM'},
  {name: 'DISC', shortName: 'DISC'},
  {name: 'DOUCHE', shortName: 'DOUCHE'},
  {name: 'DRESSING', shortName: 'DRESSING'},
  {name: 'DRUG DELIVERY SYSTEM', shortName: 'DDS'},
  {name: 'ELIXIR', shortName: 'ELIXIR'},
  {name: 'EMULSION', shortName: 'EMULSION'},
  {name: 'ENEMA', shortName: 'ENEMA'},
  {name: 'EXTRACT', shortName: 'EXTRACT'},
  {name: 'FIBER, EXTENDED RELEASE', shortName: 'FIBER ER'},
  {name: 'FILM', shortName: 'FILM'},
  {name: 'FILM, EXTENDED RELEASE', shortName: 'FILM ER'},
  {name: 'FILM, SOLUBLE', shortName: 'FILM SOLUBLE'},
  {name: 'FOR SOLUTION', shortName: 'FOR SOL'},
  {name: 'FOR SUSPENSION', shortName: 'FOR SUSP'},
  {name: 'FOR SUSPENSION, EXTENDED RELEASE', shortName: 'FOR SUSP ER'},
  {name: 'GAS', shortName: 'GAS'},
  {name: 'GEL', shortName: 'GEL'},
  {name: 'GEL, DENTIFRICE', shortName: 'GEL DENT'},
  {name: 'GEL, METERED', shortName: 'GEL MET'},
  {name: 'GENERATOR', shortName: 'GENERATOR'},
  {name: 'GLOBULE', shortName: 'GLOBULE'},
  {name: 'GRAFT', shortName: 'GRAFT'},
  {name: 'GRANULE', shortName: 'GRAN'},
  {name: 'GRANULE, DELAYED RELEASE', shortName: 'GRAN DR'},
  {name: 'GRANULE, EFFERVESCENT', shortName: 'GRAN EFFRV'},
  {name: 'GRANULE, FOR SOLUTION', shortName: 'GRAN F/SOL'},
  {name: 'GRANULE, FOR SUSPENSION', shortName: 'GRAN F/SUSP'},
  {
    name: 'GRANULE, FOR SUSPENSION, EXTENDED RELEASE',
    shortName: 'GRAN F/SUSP ER',
  },
  {name: 'GUM', shortName: 'GUM'},
  {name: 'GUM, CHEWING', shortName: 'GUM CHEWING'},
  {name: 'GUM, RESIN', shortName: 'GUM RESIN'},
  {name: 'IMPLANT', shortName: 'IMP'},
  {name: 'INHALANT', shortName: 'INHALANT'},
  {name: 'INJECTABLE, LIPOSOMAL', shortName: 'INJ LIPOS'},
  {name: 'INJECTION', shortName: 'INJ'},
  {name: 'INJECTION, EMULSION', shortName: 'INJ EMULSION'},
  {name: 'INJECTION, LIPID COMPLEX', shortName: 'INJ LIPID COMPLEX'},
  {name: 'INJECTION, POWDER, FOR SOLUTION', shortName: 'INJ PWD F/SOL'},
  {shortName: 'INJ PWD F/SUSP', name: 'INJ PWD F/SUSP'},
  {shortName: 'INJ PWD F/SUSP ER', name: 'INJ PWD F/SUSP ER'},
  {shortName: 'INJ PWD LYO F/LS', name: 'INJ PWD LYO F/LS'},
  {shortName: 'INJ PWD LYO F/SOL', name: 'INJ PWD LYO F/SOL'},
  {shortName: 'INJ PWD LYO F/SUSP', name: 'INJ PWD LYO F/SUSP'},
  {shortName: 'INJ PWD LYO F/SUSPER', name: 'INJ PWD LYO F/SUSPER'},
  {shortName: 'INJ SOL', name: 'INJ SOL'},
  {shortName: 'INJ SOL CONC', name: 'INJ SOL CONC'},
  {shortName: 'INJ SUSP', name: 'INJ SUSP'},
  {shortName: 'INJ SUSP ER', name: 'INJ SUSP ER'},
  {shortName: 'INJ SUSP LIPOS', name: 'INJ SUSP LIPOS'},
  {shortName: 'INJ SUSP SON', name: 'INJ SUSP SON'},
  {shortName: 'INSERT', name: 'INSERT'},
  {shortName: 'INSERT ER', name: 'INSERT ER'},
  {shortName: 'IUD', name: 'IUD'},
  {shortName: 'IRRIGANT', name: 'IRRIGANT'},
  {shortName: 'JELLY', name: 'JELLY'},
  {shortName: 'KIT', name: 'KIT'},
  {shortName: 'LINER DENTAL', name: 'LINER DENTAL'},
  {shortName: 'LINIMENT', name: 'LINIMENT'},
  {shortName: 'LIPSTICK', name: 'LIPSTICK'},
  {shortName: 'LIQ', name: 'LIQ'},
  {shortName: 'LIQ ER', name: 'LIQ ER'},
  {shortName: 'LOTION', name: 'LOTION'},
  {shortName: 'LOTION AUG', name: 'LOTION AUG'},
  {shortName: 'LOTION SHAMPOO', name: 'LOTION SHAMPOO'},
  {shortName: 'LOZENGE', name: 'LOZENGE'},
  {shortName: 'MOUTHWASH', name: 'MOUTHWASH'},
  {shortName: 'NOT APPLICABLE', name: 'NOT APPLICABLE'},
  {shortName: 'OIL', name: 'OIL'},
  {shortName: 'OINTMENT', name: 'OINTMENT'},
  {shortName: 'OINTMENT AUG', name: 'OINTMENT AUG'},
  {shortName: 'PACKING', name: 'PACKING'},
  {shortName: 'PASTE', name: 'PASTE'},
  {shortName: 'PASTE DENT', name: 'PASTE DENT'},
  {shortName: 'PASTILLE', name: 'PASTILLE'},
  {shortName: 'PATCH', name: 'PATCH'},
  {shortName: 'PATCH ER', name: 'PATCH ER'},
  {shortName: 'PATCH ER ELCON', name: 'PATCH ER ELCON'},
  {shortName: 'PELLET', name: 'PELLET'},
  {shortName: 'PELLET IMP', name: 'PELLET IMP'},
  {shortName: 'PELLETS COATED ER', name: 'PELLETS COATED ER'},
  {shortName: 'PILL', name: 'PILL'},
  {shortName: 'PLASTER', name: 'PLASTER'},
  {shortName: 'POULTICE', name: 'POULTICE'},
  {shortName: 'PWD', name: 'PWD'},
  {shortName: 'PWD DENT', name: 'PWD DENT'},
  {shortName: 'PWD F/SOL', name: 'PWD F/SOL'},
  {shortName: 'PWD F/SUSP', name: 'PWD F/SUSP'},
  {shortName: 'PWD MET', name: 'PWD MET'},
  {shortName: 'RING', name: 'RING'},
  {shortName: 'RINSE', name: 'RINSE'},
  {shortName: 'SALVE', name: 'SALVE'},
  {shortName: 'SHAMPOO', name: 'SHAMPOO'},
  {shortName: 'SHAMPOO SUSP', name: 'SHAMPOO SUSP'},
  {shortName: 'SOAP', name: 'SOAP'},
  {shortName: 'SOL', name: 'SOL'},
  {shortName: 'SOL CONC', name: 'SOL CONC'},
  {shortName: 'SOL F/SLUSH', name: 'SOL F/SLUSH'},
  {shortName: 'SOL GF DROPS', name: 'SOL GF DROPS'},
  {shortName: 'SOL GF ER', name: 'SOL GF ER'},
  {shortName: 'SOL DROPS', name: 'SOL DROPS'},
  {shortName: 'SPONGE', name: 'SPONGE'},
  {shortName: 'SPRAY', name: 'SPRAY'},
  {shortName: 'SPRAY MET', name: 'SPRAY MET'},
  {shortName: 'SPRAY SUSP', name: 'SPRAY SUSP'},
  {shortName: 'STICK', name: 'STICK'},
  {shortName: 'STRIP', name: 'STRIP'},
  {shortName: 'SUPP', name: 'SUPP'},
  {shortName: 'SUPP ER', name: 'SUPP ER'},
  {shortName: 'SUSP', name: 'SUSP'},
  {shortName: 'SUSP ER', name: 'SUSP ER'},
  {shortName: 'SUSP DROPS', name: 'SUSP DROPS'},
  {shortName: 'SUTURE', name: 'SUTURE'},
  {shortName: 'SWAB', name: 'SWAB'},
  {shortName: 'SYRUP', name: 'SYRUP'},
  {shortName: 'TAB', name: 'TAB'},
  {shortName: 'TAB CHEW', name: 'TAB CHEW'},
  {shortName: 'TAB COATED', name: 'TAB COATED'},
  {shortName: 'TAB COATED PART', name: 'TAB COATED PART'},
  {shortName: 'TAB DR', name: 'TAB DR'},
  {shortName: 'TAB DR PARTICLES', name: 'TAB DR PARTICLES'},
  {shortName: 'TAB DISP', name: 'TAB DISP'},
  {shortName: 'TAB EFFRV', name: 'TAB EFFRV'},
  {shortName: 'TAB ER', name: 'TAB ER'},
  {shortName: 'TAB FILM COATED', name: 'TAB FILM COATED'},
  {shortName: 'TAB FILM COATED ER', name: 'TAB FILM COATED ER'},
  {shortName: 'TAB FOR SOL', name: 'TAB FOR SOL'},
  {shortName: 'TINCTURE', name: 'TINCTURE'},
  {shortName: 'TROCHE', name: 'TROCHE'},
  {shortName: 'UNASSIGNED', name: 'UNASSIGNED'},
  {shortName: 'WAFER', name: 'WAFER'},
];
